### ISSUE TITLE
custom css timestamps?

### ISSUE THREAD

**Issue by woozy404** [taikutsunan/custom-timestamps#3]
Hey there! So I saw this:  [image](https://www.woozy.cf/images/uls60i.png)

Just wondering if this works? I might just be missing the obvious but I was changing css color and didnt see an effect

Any help appreciated!

**Comment by taikutsunan** [comment]
Most CSS colors (e.g #ff0000, rgb(255, 0, 0)) should work with the setting. If you've worked with CSS before, anything that's valid in the `color` attribute should be valid in the setting. If you change any settings, you must change channels for the change to take effect.

**Comment by woozy404** [comment]
Hey! Thanks for the response, 

I must be doing something wrong, im doing as told but it doesn't seem to work, could you give me an example in usage? Sorry again <3

**Comment by taikutsunan** [comment]
Will it not change, even when switching channels? CSS also has color terms like "white" and "blue", and if you want a more specific color, search "color picker" on Google and pick a color you like, then drop the "HEX" part into the color setting (including the #).

**Comment by woozy404** [comment]
Hey! I don't see a difference Refreshing discord or switching channels, that's why I think its me being silly and missing something obvious. I'm following everything as said

**Comment by woozy404** [comment]
Hey! Fixed it! Was just me being dumb, I didn't notice that 'var(--)' was still there, after I deleted it and just put a hex code it worked, thanks for the help
