### ISSUE TITLE
text-transform is set to uppercase on variable examples + reversed variables

### ISSUE THREAD

**Issue by NotExactlyMeButMeh** [taikutsunan/custom-timestamps#4]
The text-transform property of CSS is set to uppercase on the examples for variables such as %H (12h) and %H (24), are exactly the same in appearance.

I've also noticed that for at least the 24H/12h times that the uppercase is used for 12H which it shouldn't be, it should be for 24H as that is universal.
![image](https://user-images.githubusercontent.com/33651534/94359926-40d6cc00-00ed-11eb-9e2e-8b77ee3a052b.png)

**Comment by taikutsunan** [comment]
Oh, so it IS set to uppercase. (thanks for making it unset, theme)
I'm gonna get... right on that.
