### ISSUE TITLE
Relative Date Issue

### ISSUE THREAD

**Issue by DracoClaw** [taikutsunan/custom-timestamps#6]
When I send a message that pings my self the formatting says -1 days instead of Today
![image](https://user-images.githubusercontent.com/34274162/95787347-fe62e100-0ce1-11eb-998b-3934811bf725.png)

**Comment by DracoClaw** [comment]
Apparently it has nothing to do with me sending the message or being pinged.
![image](https://user-images.githubusercontent.com/34274162/95787462-3cf89b80-0ce2-11eb-931e-69c4c2a2b92a.png)

**Comment by taikutsunan** [comment]
This is a known issue, the relative date variables is just not very good in general. It's very approximate, and I can fix this by using the built-in Moment.JS objects.

**Comment by taikutsunan** [comment]
(it's sort of a quick-patch commit, so it's to be expected)
